# Branches that trigger a build on commit
trigger:
  branches:
    include:
    - main
    - feature/*

# Branches that trigger builds on PR
pr:
  branches:
    include:
    - main
    - feature/*

jobs:
- job: Windows
  pool:
    name: NetCore1ESPool-Public
    demands: ImageOverride -equals Build.Windows.10.Amd64.VS2019.Open
  variables:
    _os: Windows
  strategy:
    maxParallel: 2
    matrix:
      Debug:
        _configuration: Debug
      Release:
        _configuration: Release
  timeoutInMinutes: 20

  steps:
    - script: $(Build.SourcesDirectory)\eng\common\cibuild.cmd -configuration $(_configuration) -prepareMachine
      displayName: Build and Test
    - template: eng\common\templates\steps\generate-sbom.yml
    - task: PublishBuildArtifacts@1
      displayName: Publish Logs
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\artifacts\log\$(_configuration)'
        ArtifactName: '$(_os) $(_configuration)'
      continueOnError: true
      condition: not(succeeded())
